dappx/urls.py
from django.conf.urls import url
from dappx import views
from .views import EducationView,CareerView,ProjectView, \
    InternshipView,AchievementView,HobbiesView,Additional_coursesView, ProfileView, ResumeView

# SET THE NAMESPACE!
app_name = 'dappx'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    #url(r'^profile/$',views.profile,name='profile'),
    # url(r'^career/$', views.career, name='career'),
    # url(r'^education/$', views.education, name='education'),
    # url(r'^project/$', views.project, name='project'),
    # url(r'^additional/$', views.additional, name='additional'),
    # url(r'^internship/$', views.internship, name='internship'),
    # url(r'^achievement/$', views.achievement, name='achievement'),
    # url(r'^hobbie/$', views.hobbie, name='hobbie'),

    url(r'^education/$',EducationView.as_view(),name='education'),
    url(r'^career/$',CareerView.as_view(),name='career'),
    url(r'^project/$',ProjectView.as_view(),name='project'),
    url(r'^internship/$',InternshipView.as_view(),name='internship'),
    url(r'^achievement/$',AchievementView.as_view(),name='achievement'),
    url(r'^hobbie/$',HobbiesView.as_view(),name='hobbie'),
    url(r'^additional/$',Additional_coursesView.as_view(),name='additional'),
    url(r'^profile/$',ProfileView.as_view(),name='profile'),
    url(r'^resume/$',ResumeView.as_view(),name='resume'),
]

dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from dappx import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^dappx/',include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
 ]

dappx/models.py
from django.db import models
from tinymce.models import HTMLField
from django.contrib.auth.models import AbstractUser


# Create your models here.


class User(AbstractUser):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email


class Resume(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return self.name


class WorkExperience(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, blank=True)
    position = models.CharField(max_length=255, blank=True)
    company = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    achievements = HTMLField(blank=True)

    def __str__(self):
        return self.position

    class Meta:
        verbose_name_plural = "Work Experience"
        ordering = ['-end_date', ]


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.portfolio_site


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=True)
    #    job_title = models.CharField(max_length=255, blank=True)
    phone_number = models.CharField(max_length=255, blank=True)
    email = models.EmailField(max_length=255, blank=True)

    #    address = models.CharField(max_length=255, blank=True)
    #    address2 = models.CharField(max_length=255, blank=True)
    #    city = models.CharField(max_length=255, blank=True)
    #   country = CountryField(blank_label='(Select country)', blank=True)
    #    linked_in = models.CharField(max_length=255, blank=True)
    #    objective = HTMLField(blank=True)
    #   sub_expires_on = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.user.username


class Certification(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, blank=True)
    name = models.CharField(max_length=255, blank=True)

    #    date_obtained = models.DateField(null=True, blank=True)
    #    city = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name


#    class Meta:
#        ordering = ['-date_obtained', ]

class Education(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, blank=True)
    exam = models.CharField(max_length=255, blank=True)
    school = models.CharField(max_length=255, blank=True)
    degree = models.CharField(max_length=255, blank=True)
    cgpa = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.exam

    class Meta:
        verbose_name_plural = "Education"


class Career(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, blank=True)
    career = models.CharField(max_length=5000, blank=True)

    def __str__(self):
        return self.career


class Project(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, blank=True)
    project_name = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=5000, blank=True)
    role = models.CharField(max_length=255, blank=True)
    platform = models.CharField(max_length=255, blank=True)


class Additional_courses(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, blank=True)
    course_name = models.CharField(max_length=5000, blank=True)


class Internship(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, blank=True)
    company_name = models.CharField(max_length=255, blank=True)
    project_name = models.CharField(max_length=255, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)


class Achievement(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, blank=True)
    achievement = models.CharField(max_length=5000, blank=True, null=True)


class Hobbies(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, blank=True)
    hobbies = models.CharField(max_length=5000, blank=True)

dappx/views.py
from dappx.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView, ListView
from .forms import EducationForm

# from formtools.wizard.views import SessionWizardView
from .forms import (
    ResumeForm,
    WorkExperienceFormSet,
    CertificationFormSet,
    EducationForm,
    CareerForm,
    ProjectForm,
    InternshipForm,
    AchievementForm,
    HobbiesForm,
    Additional_coursesForm,
    ProfileForm,
    # CareerFormSet,
    # EducationFormSet
)
from .models import Education , Profile , Career , Project, Additional_courses, Internship, Achievement, Hobbies

class EducationView(TemplateView):
    template_name = 'dappx/education.html'
    

    def get_queryset(self, request):
        qs = Education.objects.all()
        return render(request, self.template_name, {'qs': qs })

    def get(self, request):
        form = EducationForm()
        qs = Education.objects.all()
        args = {'form': form, 'qs': qs}
        return render(request, self.template_name, args)

    def post(self, request):
        form = EducationForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            #post.resume = request.resume
            post.save()
            #text = form.cleaned_data['exam']
            form = EducationForm()
            return redirect('/dappx/education/')

        args = {'form': form}
        return render(request, self.template_name, args)


def index(request):
    return render(request, 'dappx/index.html')


class ProfileView(TemplateView):
    template_name = 'dappx/profile.html'

    def get_queryset(self, request):
        qs = Profile.objects.all()
        return render(request, self.template_name, {'qs': qs })

    def get(self, request):
        form = ProfileForm()
        qs = Profile.objects.all()
        args = {'form': form, 'qs': qs}
        return render(request, self.template_name, args)

    def post(self, request):
        form = ProfileForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            #post.resume = request.resume
            post.save()
            # text = form.cleaned_data['exam']
            form = EducationForm()
            return redirect('/dappx/profile/')

        args = {'form': form}
        return render(request, self.template_name, args)


# def profile(request):
#    return render(request,'dappx/profile.html')


class CareerView(TemplateView):
    template_name = 'dappx/career.html'

    def get_queryset(self, request):
        qs = Career.objects.all()
        return render(request, self.template_name, {'qs': qs })

    def get(self, request):
        form = CareerForm()
        qs = Career.objects.all()
        args = {'form': form, 'qs': qs}
        return render(request, self.template_name, args)

    def post(self, request):
        form = CareerForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            # post.resume = request.resume
            post.save()
            # text = form.cleaned_data['exam']
            # form = EducationForm()
            return redirect('/dappx/career/')

        args = {'form': form}
        return render(request, self.template_name, args)


# def career(request):
#    return render(request, 'dappx/career.html')


# def education(request):
#    if request.method == 'POST':
#        form = EducationForm(request.POST)
#        if form.is_valid():
#            return HttpResponseRedirect('/profile/')
#
#        else:
#            form = EducationForm()
#            form.save()
#
#    return render(request, 'dappx/education.html', {})
#
#    # return render(request,'dappx/education.html')

class ProjectView(TemplateView):
    template_name = 'dappx/project.html'

    def get_queryset(self, request):
        qs = Project.objects.all()
        return render(request, self.template_name, {'qs': qs })

    def get(self, request):
        form = ProjectForm()
        qs = Project.objects.all()
        args = {'form': form, 'qs': qs}
        return render(request, self.template_name, args)

    def post(self, request):
        form = ProjectForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            # post.resume = request.resume
            post.save()
            # text = form.cleaned_data['exam']
            # form = EducationForm()
            return redirect('/dappx/project/')

        args = {'form': form}
        return render(request, self.template_name, args)


# def project(request):
#    return render(request, 'dappx/project.html')
class Additional_coursesView(TemplateView):
    template_name = 'dappx/additional_courses.html'

    def get_queryset(self, request):
        qs = Additional_courses.objects.all()
        return render(request, self.template_name, {'qs': qs })

    def get(self, request):
        form = Additional_coursesForm()
        qs = Additional_courses.objects.all()
        args = {'form': form, 'qs': qs}
        return render(request, self.template_name, args)


    def post(self, request):
        form = Additional_coursesForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            # post.resume = request.resume
            post.save()
            # text = form.cleaned_data['exam']
            # form = EducationForm()
            return redirect('/dappx/additional/')

        args = {'form': form}
        return render(request, self.template_name, args)


# def additional(request):
#    return render(request, 'dappx/additional_courses.html')


class InternshipView(TemplateView):
    template_name = 'dappx/internship.html'

    def get_queryset(self, request):
        qs = Internship.objects.all()
        return render(request, self.template_name, {'qs': qs })

    def get(self, request):
        form = InternshipForm()
        qs = Internship.objects.all()
        args = {'form': form, 'qs': qs}
        return render(request, self.template_name, args)


    def post(self, request):
        form = InternshipForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            # post.resume = request.resume
            post.save()
            # text = form.cleaned_data['exam']
            # form = EducationForm()
            return redirect('/dappx/internship/')

        args = {'form': form}
        return render(request, self.template_name, args)


# def internship(request):
#   return render(request, 'dappx/internship.html')

class AchievementView(TemplateView):
    template_name = 'dappx/achievement.html'
    def get_queryset(self, request):
        qs = Achievement.objects.all()
        return render(request, self.template_name, {'qs': qs })

    def get(self, request):
        form = AchievementForm()
        qs = Achievement.objects.all()
        args = {'form': form, 'qs': qs}
        return render(request, self.template_name, args)


    def post(self, request):
        form = AchievementForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            # post.resume = request.resume
            post.save()
            # text = form.cleaned_data['exam']
            # form = EducationForm()
            return redirect('/dappx/achievement/')

        args = {'form': form}
        return render(request, self.template_name, args)


# def achievement(request):
#    return render(request, 'dappx/achievement.html')
class HobbiesView(TemplateView):
    template_name = 'dappx/hobbie.html'

    def get_queryset(self, request):
        qs = Hobbies.objects.all()
        return render(request, self.template_name, {'qs': qs })

    def get(self, request):
        form = HobbiesForm()
        qs = Hobbies.objects.all()
        args = {'form': form, 'qs': qs}
        return render(request, self.template_name, args)


    def post(self, request):
        form = HobbiesForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            # post.resume = request.resume
            post.save()
            # text = form.cleaned_data['exam']
            # form = EducationForm()
            return redirect('/dappx/hobbie/')

        args = {'form': form}
        return render(request, self.template_name, args)


# def achievement(request):
#    return render(request, 'dappx/achievement.html')


#def hobbie(request):
#    return render(request, 'dappx/hobbie.html')


def my_resumes(request):
    user = request.user
    # resumes = Resume.objects.filter(user=user).order_by('-created_at')
    return render(request, 'dappx/profile.html', {})


FORMS = [('resumes', ResumeForm),
         ('work_experience', WorkExperienceFormSet),
         ('certifications', CertificationFormSet),
         # ('career', CareerFormSet),
         # ('education', EducationFormSet),
         ]
FORM_TYPES = ('work_experience', 'certifications', 'education', 'career',)
TEMPLATES = {'resumes': 'dappx/profile.html',
             'work_experience': 'dappx/education.html',
             'certifications': 'dappx/additional.html',
             'education': 'dappx/education.html',
             'career': 'dappx/career.html',
             'project': 'dappx/project.html',
             'addtional_courses': 'dappx/additional.html',
             'internship': 'dappx/internship.html',
             'achievement': 'dappx/achievement.html'
             }


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == 'POST':

templates/dappx/achievement.html
{% extends "dappx/base.html" %}
{% load static %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Achievements</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit"><br>
        </form><br>
        {% for q in qs %}
        <h6>{{ q.resume }}</h6>
        <h6>Achievement: {{ q.achievements }}</h6>
        {% endfor %}

        <span onclick="newElement()" class="addBtn"> &nbsp; <button class="btn btn-primary btn-sm">Add</button></span>


        <ul id="myUL">

        </ul>


        <a class="btn btn-primary" href="/dappx/hobbie">Next</a>
    </div>
</div>

<script>
    // Create a "close" button and append it to each list item
    var myNodelist = document.getElementsByTagName("LI");
    var i;
    for (i = 0; i < myNodelist.length; i++) {
      var span = document.createElement("SPAN");
      var txt = document.createTextNode("\u00D7");
      span.className = "close";
      span.appendChild(txt);
      myNodelist[i].appendChild(span);
    }
    
    // Click on a close button to hide the current list item
    var close = document.getElementsByClassName("close");
    var i;
    for (i = 0; i < close.length; i++) {
      close[i].onclick = function() {
        var div = this.parentElement;
        div.style.display = "none";
      }
    }
    
    // Add a "checked" symbol when clicking on a list item
    var list = document.querySelector('ul');
    list.addEventListener('click', function(ev) {
      if (ev.target.tagName === 'LI') {
        ev.target.classList.toggle('checked');
      }
    }, false);
    
    // Create a new list item when clicking on the "Add" button
    function newElement() {
      var li = document.createElement("li");
      var inputValue = document.getElementById("myInput").value;
      var t = document.createTextNode(inputValue);
      li.appendChild(t);
      if (inputValue === '') {
        alert("You must write something!");
      } else {
        document.getElementById("myUL").appendChild(li);
      }
      document.getElementById("myInput").value = "";
    
      var span = document.createElement("SPAN");
      var txt = document.createTextNode("\u00D7");
      span.className = "close";
      span.appendChild(txt);
      li.appendChild(span);
    
      for (i = 0; i < close.length; i++) {
        close[i].onclick = function() {
          var div = this.parentElement;
          div.style.display = "none";
        }
      }
    }

</script>
{% endblock %}

templates/dappx/additional_courses.html
{% extends "dappx/base.html" %}
{% load static %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Additional Courses</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form><br>
        {% for q in qs %}
        <h6>{{ q.resume }}</h6>
        <h6>Additional Courses: {{ q.course_name }}</h6>
        {% endfor %}
        <span onclick="newElement()" class="addBtn"> &nbsp; <Button class="btn btn-primary btn-sm">Add</Button></span>


        <ul id="myUL">

        </ul>


        <a class="btn btn-primary" href="/dappx/internship">Next</a>
    </div>
</div>

<script>
    // Create a "close" button and append it to each list item
    var myNodelist = document.getElementsByTagName("LI");
    var i;
    for (i = 0; i < myNodelist.length; i++) {
      var span = document.createElement("SPAN");
      var txt = document.createTextNode("\u00D7");
      span.className = "close";
      span.appendChild(txt);
      myNodelist[i].appendChild(span);
    }
    
    // Click on a close button to hide the current list item
    var close = document.getElementsByClassName("close");
    var i;
    for (i = 0; i < close.length; i++) {
      close[i].onclick = function() {
        var div = this.parentElement;
        div.style.display = "none";
      }
    }
    
    // Add a "checked" symbol when clicking on a list item
    var list = document.querySelector('ul');
    list.addEventListener('click', function(ev) {
      if (ev.target.tagName === 'LI') {
        ev.target.classList.toggle('checked');
      }
    }, false);
    
    // Create a new list item when clicking on the "Add" button
    function newElement() {
      var li = document.createElement("li");
      var inputValue = document.getElementById("myInput").value;
      var t = document.createTextNode(inputValue);
      li.appendChild(t);
      if (inputValue === '') {
        alert("You must write something!");
      } else {
        document.getElementById("myUL").appendChild(li);
      }
      document.getElementById("myInput").value = "";
    
      var span = document.createElement("SPAN");
      var txt = document.createTextNode("\u00D7");
      span.className = "close";
      span.appendChild(txt);
      li.appendChild(span);
    
      for (i = 0; i < close.length; i++) {
        close[i].onclick = function() {
          var div = this.parentElement;
          div.style.display = "none";
        }
      }
    }

</script>
{% endblock %}
  

templates/dappx/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Django Resume</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            {# Django Home Link / Admin Link / Register Link#}
            <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'dappx:register' %}">Register</a></li>
            <li><a class="navbar-link" href="{% url 'dappx:profile' %}">Create Resume Here!</a></li>
            {# Some logic on what to display for last item#}
            {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a class="navbar-link" href="{% url 'dappx:user_login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block body_block %}
    {% endblock %}

</div>


</body>
</html></body>

templates/dappx/career.html
{% extends "dappx/base.html" %}
{% load static %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Career Objective</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
        {% for q in qs %}
        <h6>{{ q.resume }}</h6>
        <h6>Objecttive: {{ q.career }}</h6>

        {% endfor %}
        <div class="container">
            <a class="btn btn-primary" href="/dappx/education">Next</a>
        </div>
    </div>
</div>
{% endblock %}

templates/dappx/education.html
{% extends "dappx/base.html" %}
{% load static %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Education here</h1>
        <form  method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
        {% for q in qs %}
        <h6>{{ q.resume }}</h6>
        <h6>exam: {{ q.exam }}</h6>
        <h6>school: {{ q.school }}</h6>
        <h6>Degree: {{ q.degree }}</h6>
        <h6>cpga: {{ q.cgpa }}</h6><br>
        {% endfor %}
        <div class="container"><br>
            <a class="btn btn-primary" href="/dappx/project">Next</a>
        </div>
    </div>
</div>

{% endblock %}

templates/dappx/hobbie.html
{% extends "dappx/base.html" %}
{% load static %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Hobbies</h1>
        <form  method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form><br>
        {% for q in qs %}
        <h6>{{ q.resume }}</h6>
        <h6>Hobbies: {{ q.hobbies }}</h6>
        {% endfor %}
        <span onclick="newElement()" class="addBtn"> &nbsp; <Button class="btn btn-primary btn-sm">Add</Button></span>


        <ul id="myUL">

        </ul>


        <a class="btn btn-primary" href="/">Next</a>
    </div>
</div>

<script>
    // Create a "close" button and append it to each list item
    var myNodelist = document.getElementsByTagName("LI");
    var i;
    for (i = 0; i < myNodelist.length; i++) {
      var span = document.createElement("SPAN");
      var txt = document.createTextNode("\u00D7");
      span.className = "close";
      span.appendChild(txt);
      myNodelist[i].appendChild(span);
    }
    
    // Click on a close button to hide the current list item
    var close = document.getElementsByClassName("close");
    var i;
    for (i = 0; i < close.length; i++) {
      close[i].onclick = function() {
        var div = this.parentElement;
        div.style.display = "none";
      }
    }
    
    // Add a "checked" symbol when clicking on a list item
    var list = document.querySelector('ul');
    list.addEventListener('click', function(ev) {
      if (ev.target.tagName === 'LI') {
        ev.target.classList.toggle('checked');
      }
    }, false);
    
    // Create a new list item when clicking on the "Add" button
    function newElement() {
      var li = document.createElement("li");
      var inputValue = document.getElementById("myInput").value;
      var t = document.createTextNode(inputValue);
      li.appendChild(t);
      if (inputValue === '') {
        alert("You must write something!");
      } else {
        document.getElementById("myUL").appendChild(li);
      }
      document.getElementById("myInput").value = "";
    
      var span = document.createElement("SPAN");
      var txt = document.createTextNode("\u00D7");
      span.className = "close";
      span.appendChild(txt);
      li.appendChild(span);
    
      for (i = 0; i < close.length; i++) {
        close[i].onclick = function() {
          var div = this.parentElement;
          div.style.display = "none";
        }
      }
    }



</script>
{% endblock %}

templates/dappx/index.html
{% extends "dappx/base.html" %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Welcome to the Django Resume !</h1>
        {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        {% else %}
        <h2>Register or Login if you'd like to</h2>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/dappx/internship.html
{% extends "dappx/base.html" %}
{% load static %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Internship</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
        {% for q in qs %}
        <h6>{{ q.resume }}</h6>
        <h6>Company Name: {{ q.company_name }}</h6>
        <h6>Project Name: {{ q.project_name }}</h6>
        <h6>Start Date: {{ q.start_date }}</h6>
        <h6>End Date: {{ q.end_date }}</h6>
        {% endfor %}

        <div class="container"><br>
            <a class="btn btn-primary" href="/dappx/achievement">Next</a>
    </div>
</div>
</div>
{% endblock %}
<script>

var start = document.getElementById('start');
var end = document.getElementById('end');

start.addEventListener('change', function() {
    if (start.value)
        end.min = start.value;
}, false);
end.addEventLiseter('change', function() {
    if (end.value)
        start.max = end.value;
}, false);

</script>

templates/dappx/login.html
{% extends 'dappx/base.html' %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Login here :</h1>
        <form method="post" action="{% url 'dappx:user_login' %}">
            {% csrf_token %}
            {# A more "HTML" way of creating the login form#}
            <label for="username">Username:</label><br>
            <input type="text" name="username" placeholder="Username"><br>
            <label for="password">Password:</label><br>
            <input type="password" name="password" placeholder="Password"><br><br>
            <input type="submit" name="" value="Login"><br>
        </form>
    </div>
</div>
{% endblock %}

templates/dappx/profile.html
{% extends "dappx/base.html" %}
{% load static %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Profile </h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
        {% for q in qs %}
        <h6>{{ q.user }}</h6>
        <h6>Name: {{ q.name }}</h6>
        <h6>Phone NUmber: {{ q.phone_number }}</h6>
        <h6>Email: {{ q.email }}</h6>
        {% endfor %}
        <div class="container"><br>
            <a class="btn btn-primary" href="/dappx/career">Next</a>

        </div>
        </form>
    </div>
</div>
{% endblock %}